resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [node01]
    node01.berillo.kemrsl.ru ansible_host=${yandex_compute_instance.node01.network_interface.0.nat_ip_address}
    [node02]
    node02.berillo.kemrsl.ru ansible_host=${yandex_compute_instance.node02.network_interface.0.nat_ip_address}
    [node03]
    node03.berillo.kemrsl.ru ansible_host=${yandex_compute_instance.node03.network_interface.0.nat_ip_address}
    [node04]
    node04.berillo.kemrsl.ru ansible_host=${yandex_compute_instance.node04.network_interface.0.nat_ip_address}
    [node05]
    node05.berillo.kemrsl.ru ansible_host=${yandex_compute_instance.node05.network_interface.0.nat_ip_address}
    [node06]
    node06.berillo.kemrsl.ru ansible_host=${yandex_compute_instance.node06.network_interface.0.nat_ip_address}
    [node07]
    node07.berillo.kemrsl.ru ansible_host=${yandex_compute_instance.node07.network_interface.0.nat_ip_address}

    DOC
  filename = "../ansible/inventory"

  depends_on = [
    yandex_compute_instance.node01,
    yandex_compute_instance.node02,
    yandex_compute_instance.node03,
    yandex_compute_instance.node04,
    yandex_compute_instance.node05,
    yandex_compute_instance.node06,
    yandex_compute_instance.node07
  ]
}
